ci:
  autofix_commit_msg: '[pre-commit.ci] auto-fixes from pre-commit hooks'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-added-large-files
      args:
       - --maxkb=10000
    - id: check-merge-conflict
    - id: mixed-line-ending
      args:
       - --fix=lf
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: trailing-whitespace
